### ISSUE TITLE
Some way to run scripts on pomodoro sessions only

### ISSUE THREAD

**Issue by akdor1154** [eliostvs/tomate-exec-plugin#1]
Hey,
Thanks for this plugin and the project as a whole, you've single-handedly doubled my productivity at work :)
With the exec plugin, it'd be useful if I could only run scripts on a pomodoro session (or maybe someone else would want to run on a break session, etc).
My use case case is I have a script that asks me what I'm using the session for, I don't want to fire this when I start a break.

I can think of a few ugly ways to put this in the UI, and no decent/simple ways. I'll keep thinking of a nice way to represent this and PR if I come up with anything.

**Comment by eliostvs** [comment]
Just saw you PR. Sorry for the late response. Its a interesting idea. Let me do some tests during the weekend.

**Comment by eliostvs** [comment]
Apologies for the delay in getting back to you. I implement your suggestion but using the variables `${even} and ${type}`. For example:

```bash
some-script ${event} ${type}  # In the start of a work session this will translate to `some-script" SESSION_START POMODORO`
```

Also, I moved the plugin to [tomate-gtk](https://github.com/eliostvs/tomate-gtk) and renamed it to [Script](https://github.com/eliostvs/tomate-gtk/blob/51f422b53ac86fe4e0e130ede958b7eb8730a4d2/data/plugins/script.plugin#L2). You can see a configuration example [here](https://github.com/eliostvs/tomate-gtk/blob/master/tests/data/tomate/tomate.conf#L24). I'll archive this repository. If you still have problems, please open a issue in the [tomate-gtk](https://github.com/eliostvs/tomate-gtk) repository.
